name: Update Economic Calendar

on:
  schedule:
    # Wtorek i czwartek o 06:00 UTC
    - cron: '0 6 * * 2,4'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_ECONOMIC_CALENDAR }}  # ZMIANA: Używamy naszego PAT
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt
        
    - name: Run update script
      run: |
        python scripts/update_calendar.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push https://${{ secrets.PAT_ECONOMIC_CALENDAR }}@github.com/${{ github.repository }}.git main
